# Generated by Django 4.2.7 on 2026-01-30 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("footwear", "Footwear"),
                            ("accessory", "Accessory"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("sub_category", models.CharField(max_length=50)),
                ("color", models.CharField(db_index=True, max_length=50)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("smart_casual", "Smart Casual"),
                            ("casual", "Casual"),
                            ("sporty", "Sporty"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unisex", "Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("mid", "Mid-Range"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "products",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                            ("spring", "Spring"),
                            ("fall", "Fall"),
                            ("all", "All Seasons"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_seasons",
            },
        ),
        migrations.CreateModel(
            name="ProductOccasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("casual", "Casual"),
                            ("party", "Party"),
                            ("wedding", "Wedding"),
                            ("date", "Date"),
                            ("interview", "Interview"),
                            ("beach", "Beach"),
                            ("vacation", "Vacation"),
                            ("weekend", "Weekend"),
                            ("outdoor", "Outdoor"),
                            ("formal", "Formal"),
                            ("brunch", "Brunch"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occasions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_occasions",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "style"], name="products_categor_78ea99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "color"], name="products_categor_b17cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["style", "color"], name="products_style_5d7b46_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productseason",
            unique_together={("product", "season")},
        ),
        migrations.AlterUniqueTogether(
            name="productoccasion",
            unique_together={("product", "occasion")},
        ),
    ]
